[package]
name = "local-transfer"
version.workspace = true
edition.workspace = true

[[bin]]
name = "local-transfer"
path = "src/main.rs"

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = "0.1"

[dependencies]
transfer-core = { workspace = true }
gpui-kit = { workspace = true }
smol = { workspace = true }
uuid = { workspace = true }
chrono = "0.4"
anyhow = { workspace = true }
tracing = { workspace = true }
qrcode = "0.14"

[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.55"
tauri-winrt-notification = "0.8"

[target."cfg(windows)".dependencies]
tray-icon = "0.24.2"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
