[package]
name = "transfer-core"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1"
tokio = { workspace = true }
axum = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
tokio-util = { workspace = true }
socket2 = { workspace = true }
if-addrs = { workspace = true }
smol = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
dirs = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
http-body-util = "0.1"
zip = { version = "2", default-features = false }
http-body = "1"
